appId: com.rupee.template_two
---
- launchApp
- tapOn: "Search Stores"
- inputText: "Boutique"
- assertVisible: "Boutique\nnellore, A.P"
- tapOn: "Boutique\nnellore, A.P"
- tapOn: "Search"
- tapOn: "Search Products"
- inputText : "returnable"
- tapOn:
    id: "com.google.android.inputmethod.latin:id/0_resource_name_obfuscated"
    index: 56
- tapOn: "soch\nreturnable\n1f x 1\n₹33.66"
- assertVisible: "₹33.66"
- tapOn: "Add to bag"
- assertVisible: "Success\nItem added to cart"
- assertVisible: "Cart\n1"
- tapOn: "2f"
- assertVisible: "₹56"
- tapOn: "Add to bag"
- assertVisible: "Success\nItem added to cart"
- assertVisible: "Cart\n2"
- tapOn: "3f"
- assertVisible: "₹69"
- tapOn: "Add to bag"
- assertVisible: "Success\nItem added to cart"
- assertVisible: "Cart\n3"
- tapOn: "Cart\n3"
- assertVisible: "returnable\n1f x 1\n₹33.66"
- assertVisible: "returnable\n2f x 1\n₹56"
- assertVisible: "returnable\n3f x 1\n₹69"
- scrollUntilVisible:
    element: "Note:Cancellation must be requested 24 hours prior."
    direction: DOWN
- tapOn: "Cash On Delivery"
- tapOn: "Place Order"
- assertVisible: "Success\nOrder placed successfully"
- tapOn: "Profile"
- tapOn: "My Orders"
- tapOn: "View Order Summary"
- assertVisible: "Process\nreturnable\n₹33.66"
- assertVisible: "Process\nreturnable\n₹56"
- assertVisible: "Process\nreturnable\n₹69"
