appId: com.rupee.template_two
---
- launchApp
- tapOn: "Search Stores"
- inputText: "Boutique"
- assertVisible: "Boutique\nnellore, A.P"
- tapOn: "Boutique\nnellore, A.P"
- tapOn: "Search"
- tapOn: "Search Products"
- inputText : "non returnable"
- tapOn: "non returnable"
- tapOn: "hod\nnon returnable\nx 1\n₹21"
- tapOn: "Add to bag"
- assertVisible: "Success\nItem added to cart"
- assertVisible: "Cart\n1"
- tapOn: "Cart\n1"
- assertVisible: "non returnable\n1p x 1\n₹21"
- assertVisible: "Cart Total (1 Item)

    ₹21

    Delivery/Package

    ₹86.50

    Discount

    ₹0

    Coupon

    ₹0

    Total Savings

    ₹0

    Tax

    ₹0

    Pay

    ₹107.50"
- scrollUntilVisible:
    element: "Cash On Delivery"
    direction: DOWN
- tapOn: "Cash On Delivery"
- tapOn: "Place Order"
- assertVisible: "Success\nOrder placed successfully"
- tapOn: "Profile"
- tapOn: "My Orders"
- tapOn:
    point: "19%,25%"
- assertVisible: "Process\nreturnable\n₹33.66"
- assertVisible: "Process\nreturnable\n₹56"
- assertVisible: "Process\nreturnable\n₹69"
- tapOn: "Cancel"
- tapOn: "Yes"
- assertVisible: "Info\nItem canceled successfully."