appId: com.rupee.template_four
---
- launchApp
- tapOn: "Store name or a product..."
- tapOn: "Search Products"
- inputText: "handcrafts"
- tapOn: "HandCrafts\n0.0\nRK Beach Road"
- tapOn: "Search Products"
- inputText: "wall art"
- tapOn: "Wall Art"
# - tapOn:
#     id: "com.google.android.inputmethod.latin:id/0_resource_name_obfuscated"
#     index: 56
- tapOn: "wa\nHandcrafts\nWall Art\n₹35.30"
- assertVisible: "₹35.30"
- tapOn: "Add To Cart"
- assertVisible: "Success\nItem added to cart"
- tapOn: "fdf"
- assertVisible: "₹54.21"
- tapOn: "Add To Cart"
- tapOn: "2\nCart"
- assertVisible: "Wall Art\ndfd x 1\n₹35.30"
- assertVisible: "Wall Art\nfdf x 1\n₹54.21"
- scrollUntilVisible:
    element: "Note: Cancellation must be requested 24 hours prior."
    direction: DOWN
- assertVisible: "Cart Total (2 Item)"
- assertVisible: "₹89.51"
- tapOn: "Pay via\nSelect payment mode"
- tapOn: "Cash On Delivery"
- tapOn:
    point: "6%,7%"
- tapOn: "Place Order"
- tapOn: "Settings"
- tapOn: "My Orders"
- tapOn: "View Order Summary"
- assertVisible: "Process\nWall Art\n₹35.30"
- assertVisible: "Process\nWall Art\n₹54.21"