appId: com.rupee.template_five
---
- launchApp
- tapOn: "Search Stores"
- inputText: "Boutique"
- assertVisible: "Boutique\nnellore, A.P"
- tapOn: "Boutique\nnellore, A.P"
- tapOn: "Search"
- tapOn: "Search Products"
- inputText : "non returnable"
- tapOn:
    id: "com.google.android.inputmethod.latin:id/0_resource_name_obfuscated"
    index: 52
- assertVisible: "hod\nnon returnable\nx 1\n₹21"
- tapOn: "hod\nnon returnable\nx 1\n₹21"
- assertVisible: "₹21"
- tapOn: "Add To Cart"
- assertVisible: "Success\nItem added to cart"
- tapOn: "Cart\n1"
- assertVisible: "Cart Total (1 Item)

    ₹21

    Delivery/Package

    ₹86.50

    Discount

    ₹0

    Coupon

    ₹0

    Total Savings

    ₹0

    Tax

    ₹0.63

    Pay

    ₹108.13"
- tapOn: "Proceed to checkout"
- tapOn: "Cash On Delivery"
- tapOn: "Place Order"
- tapOn: "Profile"
- tapOn: "My Orders"
- tapOn: "View Order Summary"
- assertVisible: "Process\nnon returnable\n₹21.63"