appId: com.rupee.template_five
---
- launchApp
- tapOn: "Search Stores"
- inputText: "Boutique"
- assertVisible: "Boutique\nnellore, A.P"
- tapOn: "Boutique\nnellore, A.P"
- tapOn: "Search"
- tapOn: "Search Products"
- inputText : "returnable"
- tapOn:
    id: "com.google.android.inputmethod.latin:id/0_resource_name_obfuscated"
    index: 52
- tapOn: "soch\nreturnable\n1f x 1\n₹33.66"
- assertVisible: "₹33.66"
- tapOn: "Add To Cart"
- assertVisible: "Cart\n1"
- tapOn: "2f"
- assertVisible: "₹57.12"
- tapOn: "Add To Cart"
- assertVisible: "Cart\n2"
- tapOn: "3f"
- assertVisible: "₹70.38"
- tapOn: "Add To Cart"
- assertVisible: "Cart\n3"
- tapOn: "Cart\n3"
- assertVisible: "returnable\n1f x 1\n₹33.66"
- assertVisible: "returnable\n2f x 1\n₹57.12"
- assertVisible: "returnable\n3f x 1\n₹70.38"
- tapOn: "Proceed to checkout"
- tapOn: "Cash On Delivery"
- tapOn: "Place Order"
- assertVisible: "Success\nOrder placed successfully"
- tapOn: "Profile"
- tapOn: "My Orders"
- tapOn: "View Order Summary"
- assertVisible: "Process\nreturnable\n₹33.66"
- assertVisible: "Process\nreturnable\n₹57.12"
- assertVisible: "Process\nreturnable\n₹70.38"