appId: com.rupee.template_five
---
- launchApp
- tapOn: "Search Stores"
- inputText: "Template 5"
- assertVisible: "Template 5\nChikkamagaluru"
- tapOn: "Template 5\nChikkamagaluru"
- tapOn: "Search"
- tapOn:
    point: "50%,8%"
- inputText: "rasmalai rtn"
- tapOn: "Rasmalai Rtn"
- tapOn: "SW\nRasmalai Rtn\nx 1\n₹15.50"
- tapOn:
    point: "83%,83%"
- tapOn: "Add To Cart"
- assertVisible: "Success\nItem added to cart"
- tapOn: "Cart\n1"
- assertVisible: "Rasmalai Rtn\nr1 x 2\n₹31"
- tapOn: "Proceed to checkout"
- tapOn: "Cash On Delivery"
- tapOn: "Place Order"
- assertVisible: "Success\nOrder placed successfully"
- tapOn: "Profile"
- tapOn: "My Orders"
- tapOn: "View Order Summary"
- assertVisible: "Process\nRasmalai Rtn\n₹31"
- tapOn: "Cancel"
- tapOn: "Yes"
- extendedWaitUntil:
    visible: "View Order Summary"
    #point: "19%,25%"
    timeout: 5000      
- takeScreenshot: Images/Template5/ProductReturnable