appId: com.rupee.template_five
---
- launchApp
- tapOn: "Search Stores"
- inputText: "Template 5"
- assertVisible: "Template 5\nChikkamagaluru"
- tapOn: "Template 5\nChikkamagaluru"
- tapOn: "Search"
- tapOn:
    point: "50%,8%"
- inputText: "tandoori"
- tapOn: "Tandoori"
- tapOn: "NV\nTandoori\nl1 x 1\n₹25"
- tapOn: "Add To Cart"
- assertVisible: "Success\nItem added to cart"
- tapOn: "l2"
- tapOn: "Add To Cart"
- assertVisible: "Success\nItem added to cart"
- tapOn: "Cart\n2"
- tapOn: "Proceed to checkout"
- tapOn: "Cash On Delivery"
- tapOn: "Place Order"
- assertVisible: "Success\nOrder placed successfully"
- tapOn: "Profile"
- tapOn: "My Orders"
- tapOn: "View Order Summary"
- assertVisible: "Process\nTandoori\n₹25"
- tapOn: "Cancel"
- assertVisible: "Info\nThis item is not returnable."
- tapOn: "Scrim"
- assertVisible: "Process\nTandoori\n₹51"
- assertVisible: "Info\nThis item is not returnable."
- tapOn: "Scrim"